// @ts-ignore Generated by the OpenNext build before Wrangler bundles this file.
import handler from './.open-next/worker.js';

export default {
  fetch: handler.fetch,
  async scheduled(_event: unknown, env: Record<string, string>, ctx: { waitUntil(promise: Promise<unknown>): void }) {
    const request = new Request('https://elay-nail-bar.internal/api/cron/booking-reminders', {
      method: 'POST',
      headers: { Authorization: `Bearer ${env.CRON_SECRET}` },
    });
    ctx.waitUntil(handler.fetch(request, env, ctx));
  },
};
