import Link from 'next/link';

const manifesto=[['01','Ustalık','Her detayda ölçülü, hassas ve özenli bir uygulama yaklaşımı.'],['02','Hijyen','Bakım sürecinin her aşamasında temiz, düzenli ve yüksek standartlara önem veriyoruz.'],['03','Sadelik','Trendlerin ötesinde, size ait ve zamansız sonuçlar tasarlıyoruz.']];
const journey=[['01','Karşılama','İhtiyacınızı ve istediğiniz görünümü birlikte belirliyoruz.'],['02','Kişisel Seçim','Form, renk ve tasarımı stilinize göre şekillendiriyoruz.'],['03','Uygulama','Her aşamada detaylara ve uygulama kalitesine odaklanıyoruz.'],['04','Son Dokunuş','Temiz, dengeli ve size özel bir sonuçla tamamlıyoruz.']];
const reasons=[['01','Özen','Küçük detayların büyük fark yarattığına inanıyoruz.'],['02','Hijyen','Bakım deneyiminin temelinde temiz ve düzenli bir çalışma yaklaşımı bulunur.'],['03','Kişiselleştirme','Her tasarım kişinin stiline ve beklentisine göre şekillenir.'],['04','Zamansız Estetik','Sadece trendlere değil, size yakışan görünüme odaklanıyoruz.']];

export default function About(){return <main className="page about-page">
  <section className="about-hero"><div className="about-hero-copy"><span className="about-eyebrow">BİZİM HİKÂYEMİZ</span><h1>Güzelliği detaylarda arıyoruz.</h1><p>ELAY Nail Bar, kişisel bakımın yalnızca bir işlem değil, kendinize ayırdığınız özel bir an olduğuna inanır. Her uygulamada estetik, hijyen ve özenli işçiliği bir araya getiriyoruz.</p></div><div className="about-hero-image about-hero-real"><img src="/about-salon-real-source.png" alt="ELAY Nail Bar mağaza ve salon iç mekânı"/></div></section>
  <section className="about-manifesto">{manifesto.map(([number,title,text])=><article key={number}><b>{number}</b><h2>{title}</h2><p>{text}</p></article>)}</section>
  <section className="about-experience"><header><span className="about-eyebrow">ELAY DENEYİMİ</span><h2>Her randevu,<br/>size özel.</h2><p>Salona adım attığınız andan son dokunuşa kadar her aşamayı sakin, özenli ve kişisel bir deneyim olarak tasarlıyoruz.</p></header><div className="about-timeline">{journey.map(([number,title,text])=><article key={number}><b>{number}</b><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="about-salon"><img src="/about-salon-cinematic.png" alt="ELAY Nail Bar'ın sıcak ve mimari salon tasarımı"/><div><span className="about-eyebrow">ELAY NAIL BAR</span><h2>Sizin için tasarlanmış bir alan.</h2><p>Sıcak tonlar, doğal dokular ve sakin bir atmosfer. ELAY Nail Bar, bakım zamanınızı günlük rutinden çıkarıp kendinize ayırdığınız özel bir ana dönüştürmek için tasarlandı.</p></div></section>
  <section className="about-why"><header><span className="about-eyebrow">BİZİ FARKLI KILAN</span><h2>Neden ELAY?</h2></header><div>{reasons.map(([number,title,text])=><article key={number}><b>{number}</b><i></i><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="about-editorial"><figure className="about-editorial-main"><img src="/design-021.png" alt="ELAY nail art detayı"/></figure><figure className="about-editorial-salon"><img src="/about-salon-cinematic.png" alt="ELAY salon iç mekânı"/></figure><figure className="about-editorial-process"><img src="/about-manicure-process.png" alt="Özenli manikür uygulaması"/></figure><p><span>THE ELAY RITUAL</span>Detaylarda başlayan,<br/>size ait bir deneyim.</p></section>
  <section className="about-cta"><span>ELAY NAIL BAR</span><h2>Kendinize ayıracağınız<br/>bir sonraki an burada başlıyor.</h2><Link href="/randevu">RANDEVU AL</Link></section>
  </main>}
